name: video_cleaner
description: 极简物理洗白引擎
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_full_gpl:
    git:
      url: https://github.com/Sahad2701/ffmpeg_kit_flutter_full_gpl.git
      ref: flutter-upgrade/remove-v1-embedding
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  gal: ^2.3.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

# 告诉插件，把同目录下的 icon.png 设置为手机桌面图标
flutter_icons:
  android: true
  ios: true
  image_path: "icon.png"

flutter:
  uses-material-design: true
