name: video_cleaner
description: 极简物理洗白引擎
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # 🚀 核心武器库：原作者已删库，这里强行接管，指向社区抢救的满血版分支！
  ffmpeg_kit_flutter_full_gpl:
    git:
      url: https://github.com/Sahad2701/ffmpeg_kit_flutter_full_gpl.git
      ref: flutter-upgrade/remove-v1-embedding
      
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  gal: ^2.3.0
  permission_handler: ^11.3.0

flutter:
  uses-material-design: true
